import { NextRequest, NextResponse } from "next/server";
import { createServiceSupabase } from "@/lib/supabase/server";
import { generateDailyBriefing } from "@/lib/services/ai";
import { sendEmail } from "@/lib/services/resend";

// GET /api/cron/daily-briefing - Generate and send daily briefing (called by Vercel Cron)
export async function GET(req: NextRequest) {
  // Verify cron secret
  const authHeader = req.headers.get("authorization");
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const supabase = createServiceSupabase();
    const today = new Date().toISOString().split("T")[0];

    // Get today's metrics
    const [appointmentsRes, leadsRes, insuranceRes] = await Promise.all([
      supabase
        .from("oe_appointments")
        .select("id, status")
        .eq("appointment_date", today),
      supabase
        .from("oe_leads")
        .select("id")
        .gte("created_at", new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString()),
      supabase
        .from("oe_insurance_verifications")
        .select("id")
        .eq("status", "pending"),
    ]);

    const appointments = appointmentsRes.data || [];
    const newLeads = leadsRes.data || [];
    const pendingInsurance = insuranceRes.data || [];
    const unconfirmed = appointments.filter((a) => a.status === "scheduled").length;

    // Generate briefing via AI
    const briefing = await generateDailyBriefing({
      date: today,
      appointments: appointments.length,
      unconfirmed,
      newLeads: newLeads.length,
      pendingInsurance: pendingInsurance.length,
      yesterdayProduction: 4250, // Would come from billing integration
      yesterdayCollections: 3800,
      noShows: 0,
      aiActionsOvernight: 4,
    });

    if (briefing) {
      // Send email briefing
      await sendEmail({
        to: "dentalremind@yahoo.com",
        subject: `One Engine Daily Briefing - ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric" })}`,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="background: #0891b2; color: white; padding: 20px; border-radius: 8px 8px 0 0;">
              <h1 style="margin: 0; font-size: 20px;">One Engine Daily Briefing</h1>
              <p style="margin: 4px 0 0; opacity: 0.9;">${new Date().toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" })}</p>
            </div>
            <div style="padding: 24px; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 8px 8px;">
              <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 20px;">
                <div style="background: #f0f9ff; padding: 12px; border-radius: 8px; text-align: center;">
                  <div style="font-size: 24px; font-weight: bold; color: #0369a1;">${appointments.length}</div>
                  <div style="font-size: 12px; color: #64748b;">Appointments</div>
                </div>
                <div style="background: #f0fdf4; padding: 12px; border-radius: 8px; text-align: center;">
                  <div style="font-size: 24px; font-weight: bold; color: #15803d;">${newLeads.length}</div>
                  <div style="font-size: 12px; color: #64748b;">New Leads</div>
                </div>
              </div>
              <div style="white-space: pre-line; font-size: 14px; line-height: 1.6; color: #334155;">
                ${briefing.content}
              </div>
              <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
              <p style="font-size: 12px; color: #94a3b8; text-align: center;">
                Generated by One Engine AI Operations Platform
              </p>
            </div>
          </div>
        `,
      });

      // Log the action
      await supabase.from("oe_ai_actions").insert({
        action_type: "daily_briefing",
        module: "analytics",
        description: `Generated daily briefing for ${today}`,
        output_data: { content: briefing.content },
        status: "executed",
      });
    }

    return NextResponse.json({ success: true, briefing: briefing?.content || "AI not configured" });
  } catch (error) {
    const msg = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
